
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPERCENTleftHASHHASH NUMBER PERCENTexpression : expression HASH expression\n    | expression PERCENT expressionexpression : NUMBER'
    
_lr_action_items = {'NUMBER':([0,3,4,],[2,2,2,]),'$end':([1,2,5,6,],[0,-3,-1,-2,]),'HASH':([1,2,5,6,],[3,-3,-1,3,]),'PERCENT':([1,2,5,6,],[4,-3,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,],[1,5,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression HASH expression','expression',3,'p_expression','lab_6_2.py',45),
  ('expression -> expression PERCENT expression','expression',3,'p_expression','lab_6_2.py',46),
  ('expression -> NUMBER','expression',1,'p_expression_number','lab_6_2.py',54),
]
